<?php

namespace AppBundle\Repository;

/**
 * AnunturiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnunturiRepository extends \Doctrine\ORM\EntityRepository
{
}
