<?php

namespace AppBundle\Repository;

/**
 * CadreDidacticeCursuriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CadreDidacticeCursuriRepository extends \Doctrine\ORM\EntityRepository
{
}
