<?php

namespace AppBundle\Repository;

/**
 * CadreDidacticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CadreDidacticeRepository extends \Doctrine\ORM\EntityRepository
{
}
