<?php

namespace AppBundle\Repository;

/**
 * CadreDidacticeSerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CadreDidacticeSerieRepository extends \Doctrine\ORM\EntityRepository
{
}
