<?php

namespace AppBundle\Repository;

/**
 * CatedreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatedreRepository extends \Doctrine\ORM\EntityRepository
{
}
