<?php

namespace AppBundle\Repository;

/**
 * DateStudentiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateStudentiRepository extends \Doctrine\ORM\EntityRepository
{
}
