<?php

namespace AppBundle\Repository;

/**
 * LocatiiCursuriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocatiiCursuriRepository extends \Doctrine\ORM\EntityRepository
{
}
