<?php

namespace AppBundle\Repository;

/**
 * LocatiiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocatiiRepository extends \Doctrine\ORM\EntityRepository
{
}
