<?php

namespace AppBundle\Repository;

/**
 * ProgramaScoalaraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramaScoalaraRepository extends \Doctrine\ORM\EntityRepository
{
}
