<?php

namespace AppBundle\Repository;

/**
 * SituatieScolaraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituatieScolaraRepository extends \Doctrine\ORM\EntityRepository
{
}
