<?php

namespace AppBundle\Repository;

/**
 * SituatieScoalaraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituatieScoalaraRepository extends \Doctrine\ORM\EntityRepository
{
}
