<?php

namespace AppBundle\Repository;

/**
 * SpecializareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecializareRepository extends \Doctrine\ORM\EntityRepository
{
}
