<?php

namespace AppBundle\Repository;

/**
 * StudentiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentiRepository extends \Doctrine\ORM\EntityRepository
{
}
